server:
  port: 8188
  servlet:
    context-path: /market-auth
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/marketusersdb
    username: kolob
    password: kastor60
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
jwt:
  secret: lksjgkjsadflksadjlkfjadslkfjsdl
  lifetime: 3600000