//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.11.29 at 07:28:18 PM MSK 
//


package ru.kolobkevic.market.ws.products;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="productDtoWs" type="{http://www.kolobkevic.ru/market/ws/products}productDtoWs"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "productDtoWs"
})
@XmlRootElement(name = "getProductByIdResponse")
public class GetProductByIdResponse {

    @XmlElement(required = true)
    protected ProductDtoWs productDtoWs;

    /**
     * Gets the value of the productDtoWs property.
     * 
     * @return
     *     possible object is
     *     {@link ProductDtoWs }
     *     
     */
    public ProductDtoWs getProductDtoWs() {
        return productDtoWs;
    }

    /**
     * Sets the value of the productDtoWs property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProductDtoWs }
     *     
     */
    public void setProductDtoWs(ProductDtoWs value) {
        this.productDtoWs = value;
    }

}
